<a href="https://colab.research.google.com/github/DataRecouver/Codes-Data-Science/blob/main/C%C3%B3pia_de_Exercicios_numpyAula3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Exercícios Numpy


1 - Importe a biblioteca numpy com o alias "np"

In [ ]:
import numpy as np


2 - Crie um array qualquer e informe o tamanho deste vetor em memória.

In [ ]:
vetor=np.arange(28)
vetor
print(vetor.dtype)

int64


3 - Reduza o tamanho do array anterior em memória sem alterar ou excluir nenhum dado e exiba o novo tamanho do array.

In [ ]:
vetor = np.array([28], dtype= np.int16)
print(vetor.dtype)

int16


4 - Crie um vetor com valores de 10 a 49

In [ ]:
vetor =np.arange(10,50)
print(vetor)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


5 - Inverta o vetor anterior

In [ ]:

vetor=vetor[::-1]
print(vetor)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


6- Crie uma matriz 3x3 com valores que variam de 0 a 8

In [ ]:
vetor =np.arange(0,9).reshape(3,3)
vetor

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7- Encontre índices de elementos diferentes de zero de [1,2,0,0,4,0] (dica: tem função pronta para isso)

In [ ]:

indice=[1,2,0,0,4,0]
indice = np.array(indice)
print(np.where(indice!=0)[0])


[0 1 4]


8 - Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo, máximo, média, moda e desvio padrão.

In [ ]:
from scipy import stats

a = np.random.rand(10,10)
print("MÁXIMO = "+str(np.max(a)))
print("MÍNIMO = "+str(np.min(a)))
print("MÉDIA = "+str(np.mean(a)))
print("MEDIANA = "+str(np.median(a)))
vals,counts = np.unique(a, return_counts=True)
index = np.argmax(counts)
print("MODA = "+str(vals[index]))
print("DESVIO PADRÃO = "+str(np.std(a)))

MAXIMO = 0.9952297701840759
MINIMO = 8.566303852175494e-05
MEDIA = 0.4724516516249811
MEDIANA = 0.4945585133278978
MODA = 8.566303852175494e-05
DESVIO PADRÃO = 0.29641394128569226


In [ ]:
##TEST

import pandas as pd
import numpy as np

matriz = np.random.random(100).reshape(10,10)
print('Mínimo: {}'.format(matriz.min()))
print('Máximo: {}'.format(matriz.max()))
print('Média: {}'.format(matriz.mean()))
print('Moda:{}'.
print(matriz)


9 - Dada uma matriz 1D, multiplique por 10 todos os elementos que estão entre 3 e 8.

In [ ]:
matriz = np.arange(10)
matriz[(2 < matriz) & (matriz < 9)] *= 10
print('Editando elementos que atendem a uma condição lógica (matriz[(2 < matriz) & (matriz < 9)] *= 10):', matriz, end="\n\n")
matriz

Editando elementos que atendem a uma condição lógica (matriz[(2 < matriz) & (matriz < 9)] *= 10): [ 0  1  2 30 40 50 60 70 80  9]



array([ 0,  1,  2, 30, 40, 50, 60, 70, 80,  9])

In [ ]:
a = np.arange(10)
a[(a>3) & (a<8)] *= 10
a

array([ 0,  1,  2,  3, 40, 50, 60, 70,  8,  9])

10 - Crie uma matriz 5x5 com valores de linha variando de 0 a 4

In [ ]:
matriz = np.random.randint(5, size =(5,5))
matriz

array([[3, 4, 3, 4, 2],
       [2, 0, 0, 1, 4],
       [4, 4, 1, 2, 2],
       [4, 4, 3, 4, 0],
       [1, 3, 1, 0, 0]])

In [ ]:
np.random.rand(5,5)*4

array([[0.74363842, 0.72937178, 1.91068066, 0.35377243, 3.81113037],
       [2.03522294, 0.73162746, 1.26700256, 1.72385382, 0.39420314],
       [0.39211234, 1.36971672, 2.58115043, 2.07724641, 3.34940904],
       [0.0873528 , 1.52717742, 0.42730095, 3.49522352, 3.92446754],
       [1.36240122, 0.55868326, 2.17412315, 0.00445646, 2.0975944 ]])

11 - Crie um vetor de inteiros aleatório de tamanho 10 e ordene-o

In [ ]:
np.random.seed(1)
a = np.random.random(10)
np.sort(a)

array([1.14374817e-04, 9.23385948e-02, 1.46755891e-01, 1.86260211e-01,
       3.02332573e-01, 3.45560727e-01, 3.96767474e-01, 4.17022005e-01,
       5.38816734e-01, 7.20324493e-01])

12 - Crie o mesmo vetor da questão anterior (com o mesmo seed) e exiba a ordem de seus índices (função argsort)

In [ ]:
np.random.seed(1)
a = np.random.random(10)
a.argsort()

array([2, 5, 4, 6, 3, 7, 8, 0, 9, 1])

13 - Crie um vetor aleatório de tamanho 10 e substitua o valor máximo por 0

In [ ]:
a[np.argmax(a)] = 0
a

array([4.17022005e-01, 0.00000000e+00, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
       3.96767474e-01, 5.38816734e-01])

14 - Crie uma matriz 3x3 e exiba o índice e o valor de cada posição. (dica: consulte as funções np.ndenumerate e np.ndindex)

In [ ]:
a = np.random.rand(3,3)
for index, x in np.ndenumerate(a):
    print(index, x)
print("")
for index, x in np.ndindex(3,3):
    print(index, x)

(0, 0) 0.1981014890848788
(0, 1) 0.8007445686755367
(0, 2) 0.9682615757193975
(1, 0) 0.31342417815924284
(1, 1) 0.6923226156693141
(1, 2) 0.8763891522960383
(2, 0) 0.8946066635038473
(2, 1) 0.08504421136977791
(2, 2) 0.03905478323288236

0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2


15- Como ordenar uma matriz pela enésima coluna?

In [ ]:
coluna = 1



coluna += -1
a = np.random.rand(3,3)
print(a)
print("\n")
np.sort(a[:,coluna])[::-1]

[[0.9085955  0.29361415 0.28777534]
 [0.13002857 0.01936696 0.67883553]
 [0.21162812 0.26554666 0.49157316]]




array([0.9085955 , 0.21162812, 0.13002857])